spring:
  application:
    name: boot-meeting-service
dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: 20882
    name: dubbo
  scan:
    base-packages: org.xiaowu.boot
server:
  port: 8083
