
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/db_meeting?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: boot-meeting-service
dubbo:
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: 20881
    name: dubbo
  scan:
    base-packages: org.xiaowu.boot
server:
  port: 8082